# https://prometheus.io/docs/prometheus/latest/getting_started/

global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.

scrape_configs:
  - job_name: 'e-catalog'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      # Here we are trying to scrap metrics from service run in host os from inside docker container.
      # For linux we can use 172.17.0.1 as default host os ip. For other platforms ip can be different.
      - targets: [ '172.17.0.1:8080' ]